baseURL = "https://jwmaxwell.github.io/"
languageCode = 'en-us'
title = 'Code-Quirks'
theme = 'hermit'
paginate = 10

[params.logo]
  logoText = "Code-Quirks"
  logoHomeLink = '/home'

#[[menu.main]]
#  identifier = "blog"
#  name       = "Blog"
#  url        = "/posts"
